"""upgraded comments, added username for comments

Revision ID: d5bc358d81cf
Revises: 64b6c1ca796d
Create Date: 2026-08-08 21:24:01.641436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5bc358d81cf'
down_revision: Union[str, Sequence[str], None] = '64b6c1ca796d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('user_username', sa.String(), nullable=False))
    op.create_foreign_key(None, 'comments', 'users', ['user_username'], ['username'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'user_username')
    # ### end Alembic commands ###
